// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";
import type { AxiosError } from "axios";

import { client } from "../client.gen";
import {
  cancelCrawl,
  crawlUrls,
  getCrawlStatus,
  mapUrls,
  type Options,
  scrapeAndExtractFromUrl,
} from "../sdk.gen";
import type {
  CancelCrawlData,
  CancelCrawlError,
  CancelCrawlResponse,
  CrawlUrlsData,
  CrawlUrlsError,
  CrawlUrlsResponse,
  GetCrawlStatusData,
  GetCrawlStatusError,
  GetCrawlStatusResponse,
  MapUrlsData,
  MapUrlsError,
  MapUrlsResponse,
  ScrapeAndExtractFromUrlData,
  ScrapeAndExtractFromUrlError,
  ScrapeAndExtractFromUrlResponse,
} from "../types.gen";

/**
 * Scrape a single URL and optionally extract information using an LLM
 */
export const scrapeAndExtractFromUrlMutation = (
  options?: Partial<Options<ScrapeAndExtractFromUrlData>>,
): UseMutationOptions<
  ScrapeAndExtractFromUrlResponse,
  AxiosError<ScrapeAndExtractFromUrlError>,
  Options<ScrapeAndExtractFromUrlData>
> => {
  const mutationOptions: UseMutationOptions<
    ScrapeAndExtractFromUrlResponse,
    AxiosError<ScrapeAndExtractFromUrlError>,
    Options<ScrapeAndExtractFromUrlData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await scrapeAndExtractFromUrl({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Cancel a crawl job
 */
export const cancelCrawlMutation = (
  options?: Partial<Options<CancelCrawlData>>,
): UseMutationOptions<
  CancelCrawlResponse,
  AxiosError<CancelCrawlError>,
  Options<CancelCrawlData>
> => {
  const mutationOptions: UseMutationOptions<
    CancelCrawlResponse,
    AxiosError<CancelCrawlError>,
    Options<CancelCrawlData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await cancelCrawl({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL:
      options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getCrawlStatusQueryKey = (options: Options<GetCrawlStatusData>) =>
  createQueryKey("getCrawlStatus", options);

/**
 * Get the status of a crawl job
 */
export const getCrawlStatusOptions = (options: Options<GetCrawlStatusData>) =>
  queryOptions<
    GetCrawlStatusResponse,
    AxiosError<GetCrawlStatusError>,
    GetCrawlStatusResponse,
    ReturnType<typeof getCrawlStatusQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCrawlStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCrawlStatusQueryKey(options),
  });

/**
 * Crawl multiple URLs based on options
 */
export const crawlUrlsMutation = (
  options?: Partial<Options<CrawlUrlsData>>,
): UseMutationOptions<
  CrawlUrlsResponse,
  AxiosError<CrawlUrlsError>,
  Options<CrawlUrlsData>
> => {
  const mutationOptions: UseMutationOptions<
    CrawlUrlsResponse,
    AxiosError<CrawlUrlsError>,
    Options<CrawlUrlsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await crawlUrls({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Map multiple URLs based on options
 */
export const mapUrlsMutation = (
  options?: Partial<Options<MapUrlsData>>,
): UseMutationOptions<
  MapUrlsResponse,
  AxiosError<MapUrlsError>,
  Options<MapUrlsData>
> => {
  const mutationOptions: UseMutationOptions<
    MapUrlsResponse,
    AxiosError<MapUrlsError>,
    Options<MapUrlsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await mapUrls({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
