// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CancelCrawlData,
  CancelCrawlErrors,
  CancelCrawlResponses,
  CrawlUrlsData,
  CrawlUrlsErrors,
  CrawlUrlsResponses,
  GetCrawlStatusData,
  GetCrawlStatusErrors,
  GetCrawlStatusResponses,
  MapUrlsData,
  MapUrlsErrors,
  MapUrlsResponses,
  ScrapeAndExtractFromUrlData,
  ScrapeAndExtractFromUrlErrors,
  ScrapeAndExtractFromUrlResponses,
} from "./types.gen";
import {
  zCancelCrawlResponse,
  zCrawlUrlsResponse,
  zGetCrawlStatusResponse,
  zMapUrlsResponse,
  zScrapeAndExtractFromUrlResponse,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Scrape a single URL and optionally extract information using an LLM
 */
export const scrapeAndExtractFromUrl = <ThrowOnError extends boolean = false>(
  options: Options<ScrapeAndExtractFromUrlData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ScrapeAndExtractFromUrlResponses,
    ScrapeAndExtractFromUrlErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) =>
      await zScrapeAndExtractFromUrlResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/scrape",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Cancel a crawl job
 */
export const cancelCrawl = <ThrowOnError extends boolean = false>(
  options: Options<CancelCrawlData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    CancelCrawlResponses,
    CancelCrawlErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) =>
      await zCancelCrawlResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/crawl/{id}",
    ...options,
  });

/**
 * Get the status of a crawl job
 */
export const getCrawlStatus = <ThrowOnError extends boolean = false>(
  options: Options<GetCrawlStatusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCrawlStatusResponses,
    GetCrawlStatusErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) =>
      await zGetCrawlStatusResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/crawl/{id}",
    ...options,
  });

/**
 * Crawl multiple URLs based on options
 */
export const crawlUrls = <ThrowOnError extends boolean = false>(
  options: Options<CrawlUrlsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CrawlUrlsResponses,
    CrawlUrlsErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) =>
      await zCrawlUrlsResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/crawl",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Map multiple URLs based on options
 */
export const mapUrls = <ThrowOnError extends boolean = false>(
  options: Options<MapUrlsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MapUrlsResponses,
    MapUrlsErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => await zMapUrlsResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/map",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
