// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zScrapeResponse = z.object({
  success: z.optional(z.boolean()),
  data: z.optional(
    z.object({
      markdown: z.optional(z.string()),
      html: z.optional(z.union([z.string(), z.null()])),
      rawHtml: z.optional(z.union([z.string(), z.null()])),
      screenshot: z.optional(z.union([z.string(), z.null()])),
      links: z.optional(z.array(z.string())),
      metadata: z.optional(
        z.object({
          title: z.optional(z.string()),
          description: z.optional(z.string()),
          language: z.optional(z.union([z.string(), z.null()])),
          sourceURL: z.optional(z.url()),
          "<any other metadata> ": z.optional(z.string()),
          statusCode: z.optional(z.int()),
          error: z.optional(z.union([z.string(), z.null()])),
        }),
      ),
      llm_extraction: z.optional(
        z.union([z.record(z.string(), z.unknown()), z.null()]),
      ),
      warning: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

export const zCrawlStatusResponseObj = z.object({
  status: z.optional(z.string()),
  total: z.optional(z.int()),
  completed: z.optional(z.int()),
  expiresAt: z.optional(z.iso.datetime()),
  next: z.optional(z.union([z.string(), z.null()])),
  data: z.optional(
    z.array(
      z.object({
        markdown: z.optional(z.string()),
        rawHtml: z.optional(z.union([z.string(), z.null()])),
        links: z.optional(z.array(z.string())),
        screenshot: z.optional(z.union([z.string(), z.null()])),
        metadata: z.optional(
          z.object({
            title: z.optional(z.string()),
            description: z.optional(z.string()),
            language: z.optional(z.union([z.string(), z.null()])),
            sourceURL: z.optional(z.url()),
            "<any other metadata> ": z.optional(z.string()),
            statusCode: z.optional(z.int()),
            error: z.optional(z.union([z.string(), z.null()])),
          }),
        ),
      }),
    ),
  ),
});

export const zCrawlResponse = z.object({
  success: z.optional(z.boolean()),
  id: z.optional(z.string()),
  url: z.optional(z.url()),
});

export const zMapResponse = z.object({
  success: z.optional(z.boolean()),
  links: z.optional(z.array(z.string())),
});

export const zScrapeAndExtractFromUrlData = z.object({
  body: z.object({
    url: z.url(),
    formats: z
      .optional(
        z.array(
          z.enum([
            "markdown",
            "html",
            "rawHtml",
            "links",
            "screenshot",
            "extract",
            "screenshot@fullPage",
          ]),
        ),
      )
      .default(["markdown"]),
    includeTags: z.optional(z.array(z.string())),
    excludeTags: z.optional(z.array(z.string())),
    headers: z.optional(z.record(z.string(), z.unknown())),
    waitFor: z.optional(z.int()).default(0),
    timeout: z.optional(z.int()).default(30000),
    extract: z.optional(
      z.object({
        schema: z.optional(z.record(z.string(), z.unknown())),
        systemPrompt: z.optional(z.string()),
        prompt: z.optional(z.string()),
      }),
    ),
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful response
 */
export const zScrapeAndExtractFromUrlResponse = zScrapeResponse;

export const zCancelCrawlData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful cancellation
 */
export const zCancelCrawlResponse = z.object({
  success: z.optional(z.boolean()),
  message: z.optional(z.string()),
});

export const zGetCrawlStatusData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful response
 */
export const zGetCrawlStatusResponse = zCrawlStatusResponseObj;

export const zCrawlUrlsData = z.object({
  body: z.object({
    url: z.url(),
    excludePaths: z.optional(z.array(z.string())),
    includePaths: z.optional(z.array(z.string())),
    maxDepth: z.optional(z.int()).default(2),
    ignoreSitemap: z.optional(z.boolean()).default(true),
    limit: z.optional(z.int()).default(10),
    allowBackwardLinks: z.optional(z.boolean()).default(false),
    allowExternalLinks: z.optional(z.boolean()).default(false),
    webhookUrl: z.optional(z.url()),
    webhookMetadata: z.optional(z.record(z.string(), z.unknown())),
    scrapeOptions: z.optional(
      z.object({
        formats: z
          .optional(z.array(z.enum(["markdown", "rawHtml", "screenshot"])))
          .default(["markdown", "rawHtml"]),
        headers: z.optional(z.record(z.string(), z.unknown())),
        includeTags: z.optional(z.array(z.string())),
        excludeTags: z.optional(z.array(z.string())),
        waitFor: z.optional(z.int()).default(123),
      }),
    ),
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful response
 */
export const zCrawlUrlsResponse = zCrawlResponse;

export const zMapUrlsData = z.object({
  body: z.object({
    url: z.url(),
    search: z.optional(z.string()),
    ignoreSitemap: z.optional(z.boolean()).default(true),
    includeSubdomains: z.optional(z.boolean()).default(false),
    limit: z.optional(z.int().lte(5000)).default(5000),
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful response
 */
export const zMapUrlsResponse = zMapResponse;
